// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NewFile() {
  return window['go']['main']['App']['NewFile']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function SaveAs(arg1) {
  return window['go']['main']['App']['SaveAs'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SetDocumentState(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetDocumentState'](arg1, arg2, arg3);
}
