// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function NewFile():Promise<main.FileContent>;

export function OpenFile():Promise<main.FileContent>;

export function SaveAs(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SetDocumentState(arg1:string,arg2:boolean,arg3:string):Promise<void>;
